# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 12:54
from __future__ import unicode_literals

import dc.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField()),
                ('key', models.FileField(upload_to=dc.models.user_directory_path_key)),
                ('cert', models.FileField(blank=True, upload_to=dc.models.user_directory_path_cert)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
