# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 13:12
from __future__ import unicode_literals

import dc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='key',
            field=models.FileField(blank=True, upload_to=dc.models.user_directory_path_key),
        ),
    ]
