# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0002_auto_20160511_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 12, 8, 29, 23, 308502, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
